name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions-rs/checkout@v2
    - name: Run tests
      with: 
        toolchain: nightly
        override: true
        components: rustfmt, clippy

      run: cargo test 
