name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:

  test:
    name: rocket-test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports: ["5433:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
      
      - name: diesel install
        run: cargo install diesel_cli

      - name: diesel migration
        run: diesel migration run

      - name: Run cargo test 
        uses: actions-rs/cargo@v1
        with:
          command: test